### ISSUE TITLE
make the timeout editable within the gui

### ISSUE THREAD

**Issue by Bram-diederik** [ej52/hass-ollama-conversation#15]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ej52/hass-ollama-conversation/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I trying to make the mastadon account of my washing machine more interesting with your AI integration. 
But i have old hardware and the 60 sec timeout is to brief. 

I know waiting 2 minutes for a assist reply takes to long but its relative short generating some content during a 2 hour wash. 

### Describe the solution you'd like

make the timeout editable within the configuration

### Describe alternatives you've considered

dont see a alternative except  a wont do. 

### Additional context

https://geekdom.social/@setaggi

**Comment by ej52** [comment]
@Bram-diederik [v1.0.2](https://github.com/ej52/hass-ollama-conversation/releases/tag/v1.0.2) Now supports setting the timeout in the GUI
